theme: jekyll-theme-hacker
title: Kim
paginate: 5

author:
  name: swkim
  url:  https://SooWanKim.github.io/
  email: herosdoor@paran.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Posts:           
    - '/_posts/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - ''
    
category_path: "category" # <- default value
category_layout: "category.html" # <- default value
