# theme: jekyll-theme-hacker
# title: Kim
paginate: 5
paginate_path: /page:num/
url: https://SooWanKim.github.io/
name: "Kim"

author:
  name: swkim
  url:  https://SooWanKim.github.io/
  email: herosdoor@paran.com

category_path: "category" # <- default value
category_layout: "category.html" # <- default value

timezone:           Asia/Seoul
permalink:          /:year-:month-:day/:title/

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

  copyright:
  name:             Kim

  # Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin